### ISSUE TITLE
bookshelf chest fails to work

### ISSUE THREAD

**Issue by catlovelia** [svenhjol/CharmForge#148]
i am playing RLcraft (minecraft version 1.12.2) and I found some bookshelf chests in a village, and put them in my house just to find I cant store anything in them, the GUI still appears, I just cannot use it, nothing will go inside, I even tried shift-clicking and crafting my own bookshelf chest, nothing works

**Comment by ridjack** [comment]
This version is no longer being supported. I'd suggest checking around to see if there are any known problems within RLCraft.
