### ISSUE TITLE
Crash on startup, "Critical injection failure"

### ISSUE THREAD

**Issue by clootas** [svenhjol/CharmForge#15]
Versions
* Charm version - `2.2.1`
* Minecraft version - `1.16.4`

Description
Crash on startup, not experienced enough to understand why

Optional: Steps To Reproduce
Installed Charm-reforged & charmonium-reforged

Optional: Stacktrace/Screenshots
[latest.log](https://pastebin.com/AaX9LGBm)

**Comment by Thombias** [comment]
Same for me. Charm 2.1.9 + Charmonioum 2.1.9 load perfectly fine on my WIP 130 mods modpack, whereas version 2.2.1 for both mods immediately crash to desktop during FMLs early loading process. I don't even get a crash-log or anything.

**Comment by svenhjol** [comment]
Does your modpack include Apotheosis by any chance?

**Comment by clootas** [comment]
> 
> 
> Does your modpack include Apotheosis by any chance?

No, doesn't include Apotheosis, deleted Optifine and I still got the same crash.

**Comment by clootas** [comment]
Like the other person said, 2.1.9 works flawlessly for me

**Comment by BugmanBugman** [comment]
Do you have goblin traders by any chance? It seems to crash charm too

**Comment by BrisingrAerowing** [comment]
I have Apotheosis, and a similar loading crash.

**Comment by Thombias** [comment]
I don't have Apothesis in my modpack but i do have both Goblin Trader and OptiFine installed. Dunno if this mod could also cause an issue, but i have RandomPatches installed too, latest release version, not the beta version. (Apparently this mod is also infamous for causing issues with other mods, which is why i mentioned it here as well)

**Comment by clootas** [comment]
> 
> 
> Do you have goblin traders by any chance? It seems to crash charm too

Yeah, I have Goblin Traders

**Comment by svenhjol** [comment]
Please test this version: https://github.com/svenhjol/CharmForge/releases/download/2.2.2/charm-forge-1.16.4-2.2.2.jar

**Comment by clootas** [comment]
Works flawlessly, thanks!

**Comment by BrisingrAerowing** [comment]
It seems to be working.
