### ISSUE TITLE
Charm seems to crash on startup with Goblin Traders mod

### ISSUE THREAD

**Issue by BugmanBugman** [svenhjol/CharmForge#16]
Read me first!
1. Is your issue about the Fabric version of Charm? Please report your issue here: https://github.com/svenhjol/Charm/issues
2. We don't support Optifine! Please check that the problem still occurs if you remove Optifine from your mods.
3. Don't use the bug report to suggest new features or behavior.

Versions
* Charm version - 2.2.1
* Minecraft version - 1.16.4

Description
Charm crashes with goblin traders mod

Optional: Steps To Reproduce
Launch charm with goblin traders, it will crash

Optional: Stacktrace/Screenshots
https://hatebin.com/mwjjtwyqqt

**Comment by svenhjol** [comment]
Please test this jar file to see if it fixes the issue: https://github.com/svenhjol/CharmForge/releases/download/2.2.2/charm-forge-1.16.4-2.2.2.jar

**Comment by BugmanBugman** [comment]
Seems to have fixed it
