### ISSUE TITLE
Gold bars render solid

### ISSUE THREAD

**Issue by WenXin20** [svenhjol/CharmForge#17]
Versions
* `Charm v2.2.1`
* `Minecraft v1.16.4`
* `Forge v35.1.15`

Description
- Gold Bars are solid instead of cutout.

Optional: Screenshots

![2020-12-30_22 03 31](https://user-images.githubusercontent.com/12000593/103393907-dfa70600-4aea-11eb-8257-b7f6dd49e468.png)

**Comment by Coranthes** [comment]
Do you have optifine installed?  If so, first test without it and see if that fixes it.

**Comment by WenXin20** [comment]
Alright
