### ISSUE TITLE
Chests missing forge tags

### ISSUE THREAD

**Issue by WenXin20** [svenhjol/CharmForge#18]
Versions
* `Charm v2.2.1`
* `Minecraft v1.16.4`
* `Forge v35.1.15`

Description
- Chests are missing the block and item tag `forge:chests` and `forge:chests/wooden`, as well as the block tag `minecraft:guarded_by_piglins` (barrels & crates too).

**Comment by Coranthes** [comment]
https://github.com/svenhjol/CharmForge/releases/tag/2.2.2  I forgot about this release.  Not sure it will affect anything you're encountering, but it is the most up to date.

**Comment by WenXin20** [comment]
Oh, actually I am using v2.2.2. I just put the wrong number.

**Comment by WenXin20** [comment]
I think the block tag `minecraft:guarded_by_piglins` was missed for chests, barrels & crates
