### ISSUE TITLE
Quark incompatibility

### ISSUE THREAD

**Issue by Nazguliki** [svenhjol/CharmForge#20]
**Versions**
* Charm version - `2.2.2`
* Minecraft version - `1.16.4`
* Quark version - `r2.4-286`

**Description**
When launching minecraft with Quark and Charm together, get this crush error:
Quark (quark) encountered an error during the common_setup event phase
		java.lang.ArrayIndexOutOfBoundsException: -1

**Logs**
[debug.log](https://github.com/svenhjol/CharmForge/files/5764930/debug.log)
[latest.log](https://github.com/svenhjol/CharmForge/files/5764931/latest.log)
[crash-2021-01-04_15.41.51-fml.txt](https://github.com/svenhjol/CharmForge/files/5764932/crash-2021-01-04_15.41.51-fml.txt)

**Comment by F43nd1r** [comment]
This is a quark issue. See https://github.com/Vazkii/Quark/issues/2767. Seems like Vazkii fixed it for `LeafCarpetModule`, but you're crashing in `BlossomTreesModule`. Best report to quark with that reference.

Also note that this is a race condition and restarting your game/server should eventually work.
