### ISSUE TITLE
[1.16.4] Charm (Reforged) beyond '2.1.6' and Quark cannot be loaded together due to Quark's "big dungeon" structure

### ISSUE THREAD

**Issue by KillJestah** [svenhjol/CharmForge#25]
Charm versions past 2.1.6 will not allow the game to launch past loading up mods due to Quark's "big dungeon" structure according to a crash log.

Using Charm past 2.1.6 with Quark-r2.4-278 will cause the game to crash. Using Minecraft 1.16.4.

> Mod File: charm-forge-1.16.4-2.2.2.jar
	Failure message: Charm (charm) has failed to load correctly
		java.lang.NoClassDefFoundError: vazkii/quark/content/world/gen/structure/BigDungeonStructure
	Mod Version: 2.2.2
	Mod Issue URL: http://github.com/svenhjol/Charm/issues
	Exception message: java.lang.ClassNotFoundException: vazkii.quark.content.world.gen.structure.BigDungeonStructure

**Comment by CerbinTalYalas** [comment]
I'm using Quark-r2.4-282 and Charm 1.16.4-2.2.2 and all working fine here :)

**Comment by KillJestah** [comment]
Really?? I wonder what the issue is then, because that seems like a really odd conflict if it isn't either Quark or Charm. Occasionally, my game won't load if Charmonium is also installed with Charm and Quark. Though, with 150 mods, I guess it's probably best to dig through whichever is causing the issue.

**Comment by KillJestah** [comment]
Okay, Quark's latest release, '289' finally fixed the crash, so it was always a conflict between Quark and Charm.
