### ISSUE TITLE
Crash + Incompatibility - [Wandering Trader]

### ISSUE THREAD

**Issue by Yourname942** [svenhjol/CharmForge#29]
Versions

* Minecraft  1.16.4
* Forge 35.1.29
* Charm Reforged 2.2.2
* BetterDefaultBiomes 1.16.4-Alpha 2.5.1

Description
It seems that on line 131764 Wandering  Trader is somehow getting an exception null 
Is this incompatible with BetterDefaultBiomes?
 
Optional: Steps To Reproduce
install the mods with those versions
launch the server
crash

Logs
debug log: https://gist.github.com/Yourname942/55bff26359fe4a2d579206f5f34bed35
crash log: https://gist.github.com/Yourname942/79327a5fd200deb7066c9b689a55cdbd

**Comment by F43nd1r** [comment]
Your log shows a crash in Quark. Why do you think Charm is responsible for this?
