### ISSUE TITLE
Acquisition Enchant not disabled by config, incompatible with Fortune, can be added by Anvil but not by command

### ISSUE THREAD

**Issue by UnseenAcademical** [svenhjol/CharmForge#34]
Read me first!
1. Is your issue about the Fabric version of Charm? Please report your issue here: https://github.com/svenhjol/Charm/issues
2. We don't support Optifine! Please check that the problem still occurs if you remove Optifine from your mods.
3. Don't use the bug report to suggest new features or behavior.

Versions
Charm version 2.2.2 Reforged
Minecraft version 1.16.4

Description
The Acquisition enchantment seems to be having some difficulties. While disabled, it cannot be applied to a pickaxe via commands, but can still appear as a random enchantment or on enchanted books. If it then is added to a pickaxe, it disables the Fortune enchantment if it is also present.

Optional: Steps To Reproduce (Bold is where bug occurs)
Set "Acquisition enabled" = false
Create new world
Give diamond pickaxe
Use /enchant command to attempt to give pickaxe Acquisition
Command fails with "Diamond Pickaxe cannot support that enchantment"
Give enchanted book with Acquisition and anvil
**Use anvil to put Acquisition on pickaxe**
**Break block with Acquisition pickaxe, block is acquired even though config is turned off**
**Place enchantment table, place bookcases, enchant pickaxes until randomly acquired Acquisition
Search in-world treasure chests and mob drops, locate enchanted books and enchanted tools with Acquisition**
Enchant pickaxe with both Acquisition and Fortune (any level) using anvil
**Mine diamond ore block: one diamond appears in inventory instantly**

Optional: Stacktrace/Screenshots
By adding a stacktrace (e.g. pastebin link) and/or screenshots it helps us understand and fix the problem.

**Comment by ridjack** [comment]
Unfortunately, this is an issue that exists with all custom enchantments in Forge and is out of our hands to fix. I would recommend reporting the issue to Forge.
