### ISSUE TITLE
Husk/Stray settings don't work.

### ISSUE THREAD

**Issue by Teacyn** [svenhjol/CharmForge#36]
Versions
* Charm version - 2.2.2 (Forge)
* Minecraft version - 1.16.4

Description
The settings for Strays and Husks do not seem to work, as they still drop sand/blue ice even with it turned off.

Steps To Reproduce
Turn off Husks/Strays dropping extra items but leave on the mai ntweaks module.

Screenshots
Husks
![image](https://user-images.githubusercontent.com/12898157/104255948-2f20f680-5448-11eb-8d62-5caa77ac6862.png)
![image](https://user-images.githubusercontent.com/12898157/104255997-495ad480-5448-11eb-9440-7b00176045e9.png)

Strays
![image](https://user-images.githubusercontent.com/12898157/104256136-9b9bf580-5448-11eb-9958-06a0376fbb52.png)
![image](https://user-images.githubusercontent.com/12898157/104256146-a191d680-5448-11eb-92a8-b34f3ab9f5c2.png)

**Comment by F43nd1r** [comment]
Could not reproduce. Are you using any other mods? If so, please try to narrow it down to a minimal mod list.

**Comment by Teacyn** [comment]
Will attempt to narrow down to a smaller modlist, it could be a conflict. Will report back.

**Comment by Teacyn** [comment]
Able to reproduce using nothing but Charm + Charmonium.
![image](https://user-images.githubusercontent.com/12898157/104734741-b30c0480-570e-11eb-9d62-42d4e2416d6e.png)
![image](https://user-images.githubusercontent.com/12898157/104734761-bb643f80-570e-11eb-831a-c08eeb70fbe2.png)
![image](https://user-images.githubusercontent.com/12898157/104734804-c919c500-570e-11eb-98c9-916c977340d1.png)

**Comment by F43nd1r** [comment]
We fixed some things regarding covalent config in the [latest release](https://github.com/svenhjol/CharmForge/releases), the issue should go away if you use it.

**Comment by Teacyn** [comment]
Nope, unfortunately.

![image](https://user-images.githubusercontent.com/12898157/104857938-caebb000-58e9-11eb-84b1-a56887855a2c.png)
![image](https://user-images.githubusercontent.com/12898157/104857943-d5a64500-58e9-11eb-8ace-95157963c910.png)
![image](https://user-images.githubusercontent.com/12898157/104857945-dfc84380-58e9-11eb-869f-84e26d43dd67.png)

**Comment by F43nd1r** [comment]
Are you playing on a server? If so please make sure client and server use the same configuration.
I'm still unable to reproduce this, even after adding charmonium.

**Comment by Teacyn** [comment]
I am playing Singleplayer.

**Comment by F43nd1r** [comment]
I've been able to reproduce the issue in our dev environment. It doesn't show up every time, so it was quite hard to track down. Please test if this early build fixes the issue for you: [charm.zip](https://github.com/svenhjol/CharmForge/files/5832507/charm.zip).

**Comment by Teacyn** [comment]
> I've been able to reproduce the issue in our dev environment. It doesn't show up every time, so it was quite hard to track down. Please test if this early build fixes the issue for you: [charm.zip](https://github.com/svenhjol/CharmForge/files/5832507/charm.zip).

Yeah I noticed that only _sometimes_ would they still drop sand, it wasn't consistent at all. The testing build here seems to have fixed the problem.
