### ISSUE TITLE
Crates remove content

### ISSUE THREAD

**Issue by GhostCube22** [svenhjol/CharmForge#44]
After a short amount of time a placed crate will remove its content.

**Comment by ridjack** [comment]
Please update this bug report with more information, such as which versions you're using, which loader (Fabric or Forge), and the other basic information you can see in the template. Unless this info is added, this bug report will be closed.

**Comment by Darth-Pikachu** [comment]
> Please update this bug report with more information, such as which versions you're using, which loader (Fabric or Forge), and the other basic information you can see in the template. Unless this info is added, this bug report will be closed.

I've just encountered this issue, and found steps to easily reproduce it.

-place a crate and put items in it
-unload the chunk the crate is in (by either teleporting far away and back, relogging if on a server, or reloading the world in singleplayer)
-items in the crate are deleted

Unfortunately nothing is shown in any logs, so I can't provide more information than that.

**Comment by svenhjol** [comment]
This was an older bug in versions of Charm earlier than 2.1.10.  Please update to the latest version and try again

**Comment by Darth-Pikachu** [comment]
> This was an older bug in versions of Charm earlier than 2.1.10. Please update to the latest version and try again

obviously not, i'm using charm 2.1.9

**Comment by ridjack** [comment]
The latest Forge version on Curseforge is 2.2.2, which was posted on January 3rd.

**Comment by Darth-Pikachu** [comment]
> The latest Forge version on Curseforge is 2.2.2, which was posted on January 3rd.

no, that's the latest fabric version

**Comment by ridjack** [comment]
My dude.

https://i.imgur.com/pd9vlSH.png
![image](https://user-images.githubusercontent.com/22875626/105505874-75bbef80-5c97-11eb-971d-8771e45033e2.png)

**Comment by Darth-Pikachu** [comment]
> My dude.
> 
> https://i.imgur.com/pd9vlSH.png
> ![image](https://user-images.githubusercontent.com/22875626/105505874-75bbef80-5c97-11eb-971d-8771e45033e2.png)

ah...well that would be where all the confusion is taking place then, wouldn't it...Sorry for my stupidity.
