### ISSUE TITLE
Path to Dirt Conflicts With Quark's Shallow Dirt

### ISSUE THREAD

**Issue by Syrikal** [svenhjol/CharmForge#46]
I haven't tested this ingame, but on the website it says that right-clicking a path block with a hoe turns it into dirt. This seems like it would conflict with Quark's Shallow Dirt feature, which lets you right-click a path block with a hoe to produce shallow dirt.

**Comment by ridjack** [comment]
Please test this in-game and re-open this bug report if you find an actual conflict.
