### ISSUE TITLE
Compatibility issue between Portable Crafting module and More Crafting Tables for Forge mod

### ISSUE THREAD

**Issue by StygianEmperor** [svenhjol/CharmForge#47]
**Versions**
* charm-forge-1.16.4-2.2.2
* forge-1.16.4-35.1.37

**Description**
The Portable Crafting module doesn't recognize any items except the default crafting table, so having any other item in your inventory capable of being used as one will not put the button in your inventory.

Obviously I'm not expecting you to add every mod's variations on crafting tables to the module, but being able to add their IDs to a list in the config would be cool. Alternately, I'd even be okay with Portable Crafting just running off something like a "forge:crafting_tables" tag, even if "minecraft:crafting_table" was the only thing tagged by default, since I can figure out how to add tags to whatever with data packs.

Anyway, not a huge priority; and if I do a little more poking around with mods' source files I may be able to figure this out on my own with some reverse engineering via a text editor.

**Comment by Ephys** [comment]
I'm not sure this is fixed

https://github.com/svenhjol/CharmForge/blob/4debcafaa14bc35c7d589de3e53d68f6c9cc18cc/src/main/java/svenhjol/charm/message/ServerOpenCrafting.java#L28 this line still references the vanilla crafting table

The button does appear when a custom crafting table is tagged with `charm:crafting_tables`, but clicking it does nothing
