### ISSUE TITLE
Pre-Existing Beehives Trigger Raids

### ISSUE THREAD

**Issue by Syrikal** [svenhjol/CharmForge#48]
Versions
* Charm version - 2.2.2
* Minecraft version - e.g. 1.16.4
I _am_ using Optifine but I don't see how that could be relevant.

Description
When I have the Bad Omen status effect, raids are triggered whenever I come within a 3x3 subchunk area of any of my beehives. I believe this is because Charm adds beehives as a job site block, and a (claimed) job site block can trigger a raid. However, none of these beehives are claimed- there have been no villagers near them, ever.

This only happens with beehives that were in the world before I added Charm. Replacing them solves the issue- they do not trigger raids until claimed by a villager, at which point they begin to do so again (which is as it should be). I think that when I added Charm to the world, the mod mistakenly registered all existing beehives as claimed job site blocks.

**Comment by F43nd1r** [comment]
This isn't really a scenario we're planning to support, sorry. We advise to replace your beehives or to drink some milk.
