### ISSUE TITLE
Quark Rune end portal funtion

### ISSUE THREAD

**Issue by beeschurger** [svenhjol/CharmForge#49]
Versions
charm-forge 2.2.2
Minecraft 1.16.4
Quark-r2.4-295

Description
Coloured Runes from quark cannot be inserted into end portal frames
Eyes of ender cannot be removed while holding a coloured rune.

Optional: Steps To Reproduce
Create a new creative world, find or create an Ender portal and attempt to insert a coloured rune

Edit: Sorry, i hit the enter key while gathering version information in another window and posted this prematurely.

**Comment by svenhjol** [comment]
This functionality was never rewritten for the 1.16 version of Charm. It may come back in future.
