### ISSUE TITLE
Crate loses inventory when world reloaded

### ISSUE THREAD

**Issue by Jdewi12** [svenhjol/CharmForge#5]
Version: charm-forge-1.16.4-2.1.9
Forge: 35.1.13

Putting items in a crate, saving and quitting, then reloading the save, deletes all the items. Using `/data get block x y z` also shows no items in it after reloading the save. This happens even with only vanilla items.

Barrels still work fine still so it's specific to crates.

I've tested this in a brand new instance with only the mentioned Forge and Charm version.

**Comment by CerbinTalYalas** [comment]
Same behaviour on crates generated in Mineshaft : we started a server, and all the crates in the mineshaft were empty. Idk if this helps, but wanted to let you know :)

**Comment by svenhjol** [comment]
This should be resolved in versions after 2.1.9. The version on curseforge should fix the problem.
