### ISSUE TITLE
Bookcases Provide Enchanting Power When Empty

### ISSUE THREAD

**Issue by Syrikal** [svenhjol/CharmForge#50]
Read me first!
1. Is your issue about the Fabric version of Charm? Please report your issue here: https://github.com/svenhjol/Charm/issues
2. We don't support Optifine! Please check that the problem still occurs if you remove Optifine from your mods.
3. Don't use the bug report to suggest new features or behavior.

Versions
* Charm version - 2.2.2
* Minecraft version - e.g. 1.16.4

Description
Bookcases provide enchanting power when empty, though the website suggests they should only do so while at least one slot is occupied.

Optional: Steps To Reproduce
This helps us to repeat the issue you're having.

Place an enchanting table. Surround it with bookcases in any of the usual configurations. Try to enchant an item and see that level 30 enchantments are available.

**Comment by svenhjol** [comment]
Thanks for the report. Website has been updated with the new behavior which is that empty bookshelves do provide enchanting power.
