### ISSUE TITLE
1.15 composter feature not in 1.16 version?

### ISSUE THREAD

**Issue by EliotWL** [svenhjol/CharmForge#52]
Versions
* Charm version - e.g. `2.2.2`
* Minecraft version - e.g. `1.16.4`

Description
In Charm for 1.15 there was a config option to add other items to the list of compostable items, and a separate list of additional items that the composter could pop out in addition to the regular bone meal.  This doesn't seem to be in the config options for the 1.16.4 version.  Wasn't sure if this was intended to be lost functionality or if it was a bug.  I really loved that feature to help with compatibility for poorly made mods but understand if you removed it.

Optional: Stacktrace/Screenshots
Current config on my 1.16 server https://pastebin.com/2FA3gZ1N
Relevant section from my 1.15 config last used on my 1.15 server https://pastebin.com/02tJTTFk

**Comment by svenhjol** [comment]
This feature was never ported from 1.15. It may return in future.
