### ISSUE TITLE
Charm Mixins Json Error? Charm Forge 2.1.9

### ISSUE THREAD

**Issue by RainnMannx** [svenhjol/CharmForge#64]
[main/WARN] [mixin/]: @Mixin target net/minecraft/world/gen/feature/structure/MineshaftPieces$Corridor is public in charm.mixins.json:MineshaftPiecesMixin and should be specified in value
[main/WARN] [mixin/]: @Mixin target net/minecraft/world/gen/feature/structure/MineshaftPieces$Room is public in charm.mixins.json:MineshaftPiecesMixin and should be specified in value

Maybe minor? OCD on the log warning =P

**Comment by F43nd1r** [comment]
Duplicate of #42
