### ISSUE TITLE
Beekeeper's house spawns with Charm candles when candles are disabled

### ISSUE THREAD

**Issue by Decycle** [svenhjol/CharmForge#7]
**Versions**
* Charm version - `1.16.4-2.1.1-hotfix3`
* Minecraft version - `1.16.4`
* Loader - `Forge`

**Description**
* Beekeeper's house spawns with Charm candles when quark is present and charm candles are disabled by default.

**Comment by Coranthes** [comment]
If you have any more issues with this, you can respond here, but the fix has been implemented.
