### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Mysteriaa** [svenhjol/CharmForge#70]
Versions
* Charm version - 2.2.2
* Minecraft version - e.g. 1.16.5

Description
Game is crashing on startup. since updating to Forge 36.0.42. No crash log was generated, so here's the latest.log leading up to the crash:  https://paste.atlauncher.com/view/fa622b5d

**Comment by FynnWaelsing** [comment]
Pretty sure this is the same issue as #66.

**Comment by harmalom** [comment]
if you are using the latest version of OptiFine, that is the culprit OptiFine 1.16.5 U G7, it creates an error with charm, ("as usual"), go back to the preview_OptiFine_1.16.5_HD_U_U_G7_pre10 version, with this one it works correctly.

Log
https://pastebin.com/jMURNcTv

**Comment by Veluxidus** [comment]
I am also having the same issue. I do not have Optifine installed, so that isn't the issue.

basically any version of forge past 36.0.21 appears to cause a crash specifically with this mod.

other thread seems to indicate an issue with a data fixer.

**Comment by F43nd1r** [comment]
Duplicate of #66
