### ISSUE TITLE
Totem of undying

### ISSUE THREAD

**Issue by arms27** [svenhjol/CharmForge#78]
version: minecraft 1.16.5, forge 36.0.15, charms 2.2.2

When a player had a totem of undying in their inventory and died, the server crashed

[crash-2021-02-25_11.42.54-server.txt](https://github.com/svenhjol/CharmForge/files/6042511/crash-2021-02-25_11.42.54-server.txt)

**Comment by svenhjol** [comment]
Thank you for the report.

This has been fixed in a more recent version of Charm. Please update.
