### ISSUE TITLE
Kiln does not smelt clay into terracotta

### ISSUE THREAD

**Issue by copygirl** [svenhjol/CharmForge#82]
### Versions
- **Minecraft** `1.6.5`
- **Forge** `36.0.40`
- **Charm** `2.3.2`

### Description
The kiln seemed like the perfect block to mass-smelt clay into terracotta - like it does clay balls into bricks. Unfortunately, this doesn't appear to be possible. I did a quick check and the log did not mention any issues regarding "clay" or "terracotta".

### Screenshots
![2021-03-02_18 08 39](https://user-images.githubusercontent.com/272586/109686206-59f31580-7b82-11eb-8ead-de61cacb5444.png)

**Comment by svenhjol** [comment]
Thanks for the report. This is definitely something that we missed and should be added in the next release.
